services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ:-UTC}
      - PORT=5055
    expose:
      - 5055
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.rule=Host(`${OVERSEERR_HOSTNAME?}`)"
      - "traefik.http.routers.overseerr.entrypoints=websecure"
      - "traefik.http.routers.overseerr.tls.certresolver=letsencrypt"
    volumes:
      - ${DOCKER_DATA_DIR}/overseerr:/app/config
    profiles:
      - overseerr
      - debrid_media_server
      - all
