services:
  easynews-plus:
    image: ghcr.io/sleeyax/stremio-easynews-addon:latest
    container_name: easynews-plus
    restart: unless-stopped
    expose:
      - 1337
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.easynews-plus.rule=Host(`${EASYNEWS_PLUS_HOSTNAME?}`)"
      - "traefik.http.routers.easynews-plus.entrypoints=websecure"
      - "traefik.http.routers.easynews-plus.tls.certresolver=letsencrypt"
      - "traefik.http.routers.easynews-plus.middlewares=authelia@docker"
    profiles:
      - easynews-plus
      - stremio
      - all