services:
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    restart: unless-stopped
    expose:
      - 8080
    environment:
      DISABLE_ADDITIONAL_FEATURES: "false"
      LANGS: "en_GB"
      SECURITY_ENABLELOGIN: ${ENABLE_LOGIN:-false}
      SECURITY_INITIALLOGIN_USERNAME: "admin"
      SECURITY_INITIALLOGIN_PASSWORD: "${INITIAL_ADMIN_PASSWORD?}"
      SYSTEM_ENABLEANALYTICS: "false"
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.stirling-pdf.rule=Host(`${STIRLING_PDF_HOSTNAME?}`)"
      - "traefik.http.routers.stirling-pdf.entrypoints=websecure"
      - "traefik.http.routers.stirling-pdf.tls.certresolver=letsencrypt"
      - "traefik.http.routers.stirling-pdf.middlewares=authelia@docker"
      - "traefik.http.services.stirling-pdf.loadbalancer.server.port=8080"
    volumes:
      - ./configs:/configs
      - ./files:/customFiles/
      - ${DOCKER_DATA_DIR}/stirling-pdf/training-data:/usr/share/tessdata
      - ${DOCKER_DATA_DIR}/stirling-pdf/logs:/logs/
      - ${DOCKER_DATA_DIR}/stirling-pdf/pipeline:/pipeline/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/info/status"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    profiles:
      - stirling-pdf
      - all