services:
  easynews-plus-plus:
    image: ghcr.io/pantelx/easynews-plus-plus:latest 
    container_name: easynews-plus-plus
    restart: unless-stopped
    expose:
      - 1337
    environment:
      - EASYNEWS_LOG_LEVEL=TRACE
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.easynews-plus-plus.rule=Host(`${EASYNEWS_PLUS_PLUS_HOSTNAME}`)"
      - "traefik.http.services.easynews-plus-plus.loadbalancer.server.port=1337"
      - "traefik.http.routers.easynews-plus-plus.entrypoints=websecure"
      - "traefik.http.routers.easynews-plus-plus.tls=true"
      - "traefik.http.routers.easynews-plus-plus.tls.certresolver=letsencrypt"
      - "traefik.http.routers.easynews-plus-plus.middlewares=authelia@docker"
    volumes:
      - ${DOCKER_DATA_DIR}/easynews-plus-plus/custom-titles.json:/app/custom-titles.json
    profiles:
      - all
      - easynews-plus-plus
