services:
  watchlist:
    container_name: plex_watchlist_service
    image: ghcr.io/westsurname/scripts/watchlist:latest
    volumes:
      - ${DOCKER_DATA_DIR}/wests-scripts/shared/tokens.json:/app/shared/tokens.json
    env_file:
      - ../.env
    restart: unless-stopped
    depends_on:
      plex:
        condition: service_healthy
      plex_authentication:
        condition: service_started
    profiles:
      - all
      - plex_watchlist