services:
  sshbot:
    image: nhyyeb/sshbot:latest
    container_name: sshbot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TZ: ${TZ:-UTC}
      # SSH_PRIVATE_KEY: |
      #   -----BEGIN OPENSSH PRIVATE KEY-----
      #   your_key_line_1
      #   your_key_line_2
      #   your_key_line_3
      #   -----END OPENSSH PRIVATE KEY-----
    profiles:
      - sshbot
      - all
    
