services:
  notifiarr:
    image: golift/notifiarr
    container_name: notifiarr
    restart: unless-stopped
    expose:
      - 5454
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notifiarr.rule=Host(`${NOTIFIARR_HOSTNAME?}`)"
      - "traefik.http.routers.notifiarr.entrypoints=websecure"
      - "traefik.http.routers.notifiarr.tls.certresolver=letsencrypt"
      - "traefik.http.routers.notifiarr.middlewares=crowdsec@docker"
    volumes:
      - ${DOCKER_DATA_DIR}/notifiarr:/config
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id
    profiles:
      - notifiarr
      - all