services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    restart: unless-stopped
    user: ${PUID}:${PGID}
    command:
      - serve
    expose:
      - 80
    environment:
      TZ: ${TZ}
      NTFY_BASE_URL: "https://${NTFY_HOSTNAME?}"
      NTFY_BEHIND_PROXY: "true"
      NTFY_ENABLE_LOGIN: "true"
      NTFY_ENABLE_SIGNUP: "${ENABLE_SIGNUP:-true}"
      NTFY_AUTH_DEFAULT_ACCESS: "deny-all"
      NTFY_UPSTREAM_BASE_URL: https://ntfy.sh
      NTFY_WEB_PUSH_PUBLIC_KEY: "${WEB_PUSH_PUBLIC_KEY}"
      NTFY_WEB_PUSH_PRIVATE_KEY: "${WEB_PUSH_PRIVATE_KEY}"
      NTFY_WEB_PUSH_EMAIL_ADDRESS: "${WEB_PUSH_EMAIL_ADDRESS}"
      NTFY_AUTH_FILE: "/var/lib/ntfy/auth.db"
      NTFY_CACHE_FILE: "/var/lib/ntfy/cache.db"
      NTFY_WEB_PUSH_FILE: "/var/lib/ntfy/webpush.db"
      NTFY_ATTACHMENT_CACHE_DIR: "/var/lib/ntfy/attachments"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ntfy.rule=Host(`${NTFY_HOSTNAME?}`)"
      - "traefik.http.routers.ntfy.entrypoints=websecure"
      - "traefik.http.routers.ntfy.tls.certresolver=letsencrypt"
      - "traefik.http.services.ntfy.loadbalancer.server.port=80"
    volumes:
      - ${DOCKER_DATA_DIR}/ntfy:/var/lib/ntfy
    healthcheck:
      test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    profiles:
      - ntfy
      - all