services:
  actual-budget:
    image: actualbudget/actual-server:latest
    container_name: actual-budget
    restart: unless-stopped
    expose:
      - 5006
    environment:
      ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB: "${UPLOAD_FILE_SYNC_SIZE_LIMIT}"
      ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB: "${UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT}"
      ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB: "${UPLOAD_FILE_SIZE_LIMIT}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.actual-budget.rule=Host(`${ACTUAL_BUDGET_HOSTNAME?}`)"
      - "traefik.http.routers.actual-budget.entrypoints=websecure"
      - "traefik.http.routers.actual-budget.tls.certresolver=letsencrypt"
      - "traefik.http.routers.actual-budget.middlewares=authelia@docker"
      - "traefik.http.services.actual-budget.loadbalancer.server.port=5006"
    volumes:
      - ${DOCKER_DATA_DIR}/actual-budget:/data
    healthcheck:
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    profiles: 
      - actual-budget
      - all
