services:
  anime-kitsu:
    build:
      context: https://github.com/TheBeastLT/stremio-kitsu-anime.git
      dockerfile: Dockerfile
    image: anime-kitsu:latest
    container_name: anime-kitsu
    expose:
      - 7000
    environment:
      - PORT=7000
      - ADDON_URL=https://${ANIME_KITSU_HOSTNAME}
      - FANART_APIKEY=${FANART_APIKEY}
      - META_TTL=86400
      - CATALOG_TTL=86400
      - CACHE_MAX_AGE=43200
      - MONGO_URI=mongodb://anime-kitsu_mongo:27017/anime-kitsu
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.anime-kitsu.rule=Host(`${ANIME_KITSU_HOSTNAME}`)"
      - "traefik.http.services.anime-kitsu.loadbalancer.server.port=7000"
      - "traefik.http.routers.anime-kitsu.entrypoints=websecure"
      - "traefik.http.routers.anime-kitsu.tls=true"
      - "traefik.http.routers.anime-kitsu.tls.certresolver=letsencrypt"
      - "traefik.http.routers.anime-kitsu.middlewares=authelia@docker"
    volumes:
      - ${DOCKER_DATA_DIR}/anime-kitsu/imdb_mapping.json:/home/node/app/static/data/imdb_mapping.json
    profiles:
      - anime-kitsu
      - stremio
      - all

  anime-kitsu_mongo:
    image: mongo:latest
    container_name: anime-kitsu_mongo
    restart: unless-stopped
    volumes:
      - ${DOCKER_DATA_DIR}/anime-kitsu/db:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    profiles:
      - anime-kitsu
      - stremio
      - all


