services:
  karakeep:
    image: ghcr.io/karakeep-app/karakeep:${KARAKEEP_VERSION:-release}
    container_name: karakeep
    restart: unless-stopped
    expose:
      - 3000
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://karakeep_meilisearch:7700
      BROWSER_WEB_URL: http://karakeep_chrome:9222
      DATA_DIR: /data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.karakeep.rule=Host(`${KARAKEEP_HOSTNAME?}`)"
      - "traefik.http.routers.karakeep.entrypoints=websecure"
      - "traefik.http.routers.karakeep.tls.certresolver=letsencrypt"
      - "traefik.http.services.karakeep.loadbalancer.server.port=3000"
    volumes:
      - ${DOCKER_DATA_DIR}/karakeep:/data
    profiles:
      - karakeep
      - all
  karakeep_chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    container_name: karakeep_chrome
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    expose:
      - 9222
    profiles:
      - karakeep
      - all
  karakeep_meilisearch:
    image: getmeili/meilisearch:v1.13.3
    container_name: karakeep_meilisearch
    restart: unless-stopped
    expose:
      - 7700
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - ${DOCKER_DATA_DIR}/karakeep/meili:/meili_data
    profiles:
      - karakeep
      - all

