services:
  honey:
    image: ghcr.io/dani3l0/honey:latest
    container_name: honey
    restart: unless-stopped
    user: $PUID:$PGID
    volumes:
      - ./config.json:/app/dist/config/config.json
      - ${DOCKER_DATA_DIR}/honey:/app/dist/img/custom # place any images in this folder, and use custom/image_name.jpg in the config.json
    expose:
      - 4173
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.honey.rule=Host(`${HONEY_HOSTNAME?}`)"
      - "traefik.http.routers.honey.entrypoints=websecure"
      - "traefik.http.routers.honey.tls.certresolver=letsencrypt"
      - "traefik.http.routers.honey.middlewares=authelia@docker"
    profiles:
      - honey
      - all
