services:
  discord-tickets:
    image: eartharoid/discord-tickets:4.0
    container_name: discord-tickets
    restart: unless-stopped
    expose:
      - 8169
    tty: true
    stdin_open: true
    environment:
      DB_CONNECTION_URL: mysql://tickets:${MYSQL_PASSWORD?}@discord-tickets_mysql:3306/tickets
      DISCORD_SECRET: ${DISCORD_SECRET?}
      DISCORD_TOKEN: ${DISCORD_TOKEN?}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY?}
      DB_PROVIDER: mysql
      HTTP_EXTERNAL: https://${DISCORD_TICKETS_HOSTNAME?}
      HTTP_HOST: 0.0.0.0
      # HTTP_INTERNAL: http://discord-tickets:8169
      HTTP_INTERNAL: http://localhost:8169
      HTTP_PORT: 8169
      HTTP_TRUST_PROXY: "true"
      INVALIDATE_TOKENS:
      OVERRIDE_ARCHIVE: null
      PUBLIC_BOT: "false"
      PUBLISH_COMMANDS: "false"
      SUPER: ${SUPER_USERS?}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.discord-tickets.rule=Host(`${DISCORD_TICKETS_HOSTNAME?}`)"
      - "traefik.http.routers.discord-tickets.entrypoints=websecure"
      - "traefik.http.routers.discord-tickets.tls.certresolver=letsencrypt"
      - "traefik.http.services.discord-tickets.loadbalancer.server.port=8169"
    volumes:
      - ${DOCKER_DATA_DIR}/discord-tickets:/home/container/user
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      discord-tickets_mysql:
        condition: service_healthy
    profiles:
      - discord-tickets
      - all
    
  discord-tickets_mysql:
    image: mysql:8
    container_name: discord-tickets_mysql
    restart: unless-stopped
    volumes:
      - ${DOCKER_DATA_DIR}/discord-tickets/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: tickets
      MYSQL_PASSWORD: ${MYSQL_PASSWORD?}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD?}
      MYSQL_USER: tickets
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u tickets --password=${MYSQL_PASSWORD?}"]
      start_period: 30s
      interval: 30s
      retries: 5
    profiles:
      - discord-tickets
      - all
