services:
  stremio-streaming-catalogs:
    image: stremio-streaming-catalogs
    container_name: stremio-streaming-catalogs
    restart: unless-stopped
    build:
      context: https://github.com/rleroi/Stremio-Streaming-Catalogs-Addon.git
      dockerfile_inline: |
        FROM node:22.17-alpine
        WORKDIR /app

        COPY package*.json ./

        # Install production dependencies only
        RUN npm ci --omit=dev --ignore-scripts && \
            npm cache clean --force

        # Copy application files
        COPY vue ./vue
        COPY index.js addon.js ./

        ENV NODE_ENV=production

        ENTRYPOINT ["npm", "start"]
    expose:
      - 7700
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stremio-streaming-catalogs.rule=Host(`${STREMIO_STREAMING_CATALOGS_HOSTNAME?}`)"
      - "traefik.http.routers.stremio-streaming-catalogs.entrypoints=websecure"
      - "traefik.http.routers.stremio-streaming-catalogs.tls.certresolver=letsencrypt"
      - "traefik.http.services.stremio-streaming-catalogs.loadbalancer.server.port=7700"
      - "traefik.http.routers.stremio-streaming-catalogs.middlewares=authelia@docker"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:7700/manifest.json",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - stremio-streaming-catalogs
      - all
