services:
  omg-tv-stremio-addon:
    build:
      context: https://github.com/mccoy88f/OMG-Premium-TV.git
      dockerfile: Dockerfile
    image: omg-tv-stremio-addon
    container_name: omg-tv-stremio-addon
    restart: unless-stopped
    expose:
      - 7860
    environment:
      - PORT=7860
      - HOST=0.0.0.0  
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.omg-tv-stremio-addon.rule=Host(`${OMG_TV_STREMIO_ADDON_HOSTNAME?}`)"
      - "traefik.http.routers.omg-tv-stremio-addon.entrypoints=websecure"
      - "traefik.http.routers.omg-tv-stremio-addon.tls.certresolver=letsencrypt"
      - "traefik.http.routers.omg-tv-stremio-addon.middlewares=authelia@docker"
      - "traefik.http.services.omg-tv-stremio-addon.loadbalancer.server.port=7860"
    profiles: 
      - omg-tv-stremio-addon
      - stremio
      - all
