services:
  seanime:
    image: umagistr/seanime
    container_name: seanime
    volumes:
      - /mnt/user/anime:/anime
      - /mnt/user/downloads:/downloads
      - /mnt:/mnt:rslave
      - ${DOCKER_DATA_DIR}/seanime:/root/.config/Seanime
    expose:
      - 43211
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.seanime.rule=Host(`${SEANIME_HOSTNAME?}`)"
      - "traefik.http.routers.seanime.entrypoints=websecure"
      - "traefik.http.routers.seanime.tls.certresolver=letsencrypt"
      - "traefik.http.routers.seanime.middlewares=authelia@docker"
    healthcheck:
      test: wget -qO- http://localhost:43211/api/v1/status
      interval: 5m
      timeout: 10s
      retries: 5
      start_period: 10s
    profiles:
      - seanime
      - all
