services:
  stremio-letterboxd:
    image: stremio-letterboxd
    build:
      context: https://github.com/megadrive/stremio-letterboxd.git
      dockerfile_inline: |
        FROM node:22.14.0

        ENV NODE_ENV=production

        WORKDIR /app

        COPY . .

        # Change Prisma provider to sqlite
        RUN sed -i 's/provider = "postgresql"/provider = "sqlite"/' packages/database/prisma/schema.prisma

        RUN npm install -g pnpm@10.5.0 && pnpm install

        RUN pnpm -w prisma:generate

        RUN pnpm build

        ENV DATABASE_URL=${DATABASE_URL}

        RUN pnpm run --filter @stremio-addon/database prisma migrate dev --name init --create-only

        # RUN MIGRATIONS AND START
        ENTRYPOINT  ["sh", "-c", "pnpm run --filter @stremio-addon/database prisma migrate deploy && pnpm start"]
    container_name: stremio-letterboxd
    restart: unless-stopped
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stremio-letterboxd.rule=Host(`${STREMIO_LETTERBOXD_HOSTNAME}`)"
      - "traefik.http.routers.stremio-letterboxd.entrypoints=websecure"
      - "traefik.http.routers.stremio-letterboxd.tls.certresolver=letsencrypt"
      - "traefik.http.services.stremio-letterboxd.loadbalancer.server.port=3000"
      - "traefik.http.routers.stremio-letterboxd.middlewares=authelia@docker"
    volumes:
      - ${DOCKER_DATA_DIR}/stremio-letterboxd:/app/data
    profiles:
      - stremio
      - stremio-letterboxd
      - all