services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ:-Etc/UTC}
      - DISPLAY_TIMEZONE=${TZ:-Etc/UTC}
      - APP_KEY=${APP_KEY?}
      - DB_CONNECTION=sqlite
      - PUBLIC_DASHBOARD=true
      - APP_URL=https://${SPEEDTEST_TRACKER_HOSTNAME?}
      - ASSET_URL=https://${SPEEDTEST_TRACKER_HOSTNAME?}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.speedtest-tracker.rule=Host(`${SPEEDTEST_TRACKER_HOSTNAME?}`)"
      - "traefik.http.routers.speedtest-tracker.entrypoints=websecure"
      - "traefik.http.routers.speedtest-tracker.tls.certresolver=letsencrypt"
      - "traefik.http.routers.speedtest-tracker.middlewares=authelia@docker"
      - "traefik.http.services.speedtest-tracker.loadbalancer.server.port=80"
    volumes:
      - ${DOCKER_DATA_DIR}/speedtest-tracker:/config
    profiles:
      - speedtest-tracker
      - all

