services:
  stremio-catalog-providers:
    image: reddravenn/stremio-catalog-providers
    container_name: stremio-catalog-providers
    expose:
      - 7000
    environment:
      PORT: 7000
      BASE_URL: https://${STREMIO_CATALOG_PROVIDERS_HOSTNAME?}
      DB_USER: postgres
      DB_HOST: stremio-catalog-providers_postgres
      DB_NAME: stremio_catalog_db
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_MAX_CONNECTIONS: 20
      DB_IDLE_TIMEOUT: 30000
      DB_CONNECTION_TIMEOUT: 2000
      REDIS_HOST: stremio-catalog-providers_redis
      REDIS_PORT: 6379
      REDIS_PASSWORD:
      TRAKT_CLIENT_ID: ${TRAKT_CLIENT_ID?}
      TRAKT_CLIENT_SECRET: ${TRAKT_CLIENT_SECRET?}
      TRAKT_HISTORY_FETCH_INTERVAL: 1d
      CACHE_CATALOG_CONTENT_DURATION_DAYS: 1
      CACHE_POSTER_CONTENT_DURATION_DAYS: 7
      LOG_LEVEL: info
      LOG_INTERVAL_DELETION: 3d
      NODE_ENV: production
    depends_on:
      stremio-catalog-providers_postgres:
        condition: service_healthy
      stremio-catalog-providers_redis:
        condition: service_healthy
    volumes:
      - ${DOCKER_DATA_DIR}/stremio-catalog-providers/logs:/usr/src/app/log
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ravenn-catalogs.rule=Host(`${STREMIO_CATALOG_PROVIDERS_HOSTNAME?}`)"
      - "traefik.http.routers.ravenn-catalogs.entrypoints=websecure"
      - "traefik.http.routers.ravenn-catalogs.tls.certresolver=letsencrypt"
      - "traefik.http.routers.ravenn-catalogs.middlewares=authelia@docker"
    profiles:
      - stremio-catalog-providers
      - stremio
      - all  
      
  stremio-catalog-providers_postgres:
    container_name: stremio-catalog-providers_postgres
    image: postgres:16.4
    environment:
      POSTGRES_DB: stremio_catalog_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ${DOCKER_DATA_DIR}/stremio-catalog-providers/db:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d stremio_catalog_db"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    profiles:
      - stremio-catalog-providers
      - stremio
      - all

  stremio-catalog-providers_redis:
    container_name: stremio-catalog-providers_redis
    image: redis:6
    expose:
      - 6379
    volumes:
      - ${DOCKER_DATA_DIR}/stremio-catalog-providers/cache:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    profiles:
      - stremio-catalog-providers
      - stremio
      - all
