services:
  huntarr:
    image: huntarr/huntarr:latest
    container_name: huntarr
    restart: unless-stopped
    expose:
      - 9705
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.huntarr.rule=Host(`${HUNTARR_HOSTNAME?}`)"
      - "traefik.http.routers.huntarr.entrypoints=websecure"
      - "traefik.http.routers.huntarr.tls.certresolver=letsencrypt"
      - "traefik.http.routers.huntarr.middlewares=authelia@docker"
    volumes:
      - ${DOCKER_DATA_DIR?}/huntarr:/config
    profiles:
      - huntarr
      - all