services:
  aiostremio:
    image: viren070/aiostremio:latest
    container_name: aiostremio
    restart: unless-stopped
    expose:
      - 8469
    volumes:
     - ./config.json:/app/data/config.json
     - ${DOCKER_DATA_DIR}/aiostremio/db:/app/db
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aiostremio.rule=Host(`${AIOSTREMIO_HOSTNAME?}`)"
      - "traefik.http.routers.aiostremio.entrypoints=websecure"
      - "traefik.http.routers.aiostremio.tls.certresolver=letsencrypt"
      - "traefik.http.routers.aiostremio.middlewares=authelia@docker"
    profiles:
      - aiostremio
      - stremio
      - all
    depends_on:
      aiostremio_redis:
        condition: service_healthy
  
  aiostremio_redis: 
    image: redis:latest
    container_name: aiostremio_redis
    restart: unless-stopped
    volumes:
      - ${DOCKER_DATA_DIR}/aiostremio/cache:/data
    command: redis-server --appendonly yes --save 60 1
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - aiostremio
      - stremio
      - all
