services:
  it-tools:
    image: ghcr.io/corentinth/it-tools:latest
    container_name: it-tools
    restart: unless-stopped
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.it-tools.rule=Host(`${IT_TOOLS_HOSTNAME?}`)"
      - "traefik.http.routers.it-tools.entrypoints=websecure"
      - "traefik.http.routers.it-tools.tls.certresolver=letsencrypt"
      - "traefik.http.routers.it-tools.middlewares=authelia@docker"
      - "traefik.http.services.it-tools.loadbalancer.server.port=80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    profiles:
      - it-tools
      - all
          
