services:
  thelounge:
    image: ghcr.io/thelounge/thelounge:latest
    container_name: thelounge
    restart: unless-stopped
    user: ${PUID}:${PGID}
    expose:
      - 9000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.thelounge.rule=Host(`${THE_LOUNGE_HOSTNAME?}`)"
      - "traefik.http.routers.thelounge.entrypoints=websecure"
      - "traefik.http.routers.thelounge.tls.certresolver=letsencrypt"
      - "traefik.http.routers.thelounge.middlewares=authelia@docker"
    volumes:
      - ${DOCKER_DATA_DIR}/thelounge:/var/opt/thelounge 
    profiles:
      - thelounge
      - all

