x-plextraktsync:
  &plextraktsync
  image: ghcr.io/taxel/plextraktsync
  container_name: plextraktsync
  restart: on-failure:2
  volumes:
    - ${DOCKER_DATA_DIR}/plextraktsync/1:/app/config
  environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=${TZ:-Etc/UTC}
  profiles:
    - plextraktsync
    - all

x-plextraktsync_sync:
  &plextraktsync_sync
  <<: *plextraktsync
  command: sync


x-plextraktsync_scrobble:
  &plextraktsync_scrobble
  <<: *plextraktsync
  command: watch

  

services:
  plextraktsync_scheduler:
    image: mcuadros/ofelia:0.3
    container_name: plextraktsync_scheduler
    restart: unless-stopped
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.plextraktsync-1.schedule: "@every 6h"
      ofelia.job-run.plextraktsync-1.container: "plextraktsync_1_sync"
      # ofelia.job-run.plextraktsync-2.schedule: "@every 6h"
      # ofelia.job-run.plextraktsync-2.container: "plextraktsync_2_sync"
    profiles:
      - plextraktsync
      - all

  plextraktsync_1_sync:
    <<: *plextraktsync_sync
    container_name: plextraktsync_1_sync


  plextraktsync_1_scrobble:
    <<: *plextraktsync_scrobble
    container_name: plextraktsync_1_scrobble

  # plextraktsync_2_sync:
  #   <<: *plextraktsync_sync
  #   container_name: plextraktsync_2_sync
  #   volumes:
  #     - ${DOCKER_DATA_DIR}/plextraktsync/2:/app/config
  #   profiles:
  #     - plextraktsync_2
  #     - all

  # plextraktsync_2_scrobble:
  #   <<: *plextraktsync_scrobble
  #   container_name: plextraktsync_2_scrobble
  #   volumes:
  #     - ${DOCKER_DATA_DIR}/plextraktsync/2:/app/config
  #   profiles:
  #     - plextraktsync_2
  #     - all
    
