services:
  quetre:
    build:
      context: https://github.com/zyachel/quetre.git
      dockerfile_inline: |
        FROM node:alpine3.17
        WORKDIR /app
        COPY . .
        ENV NODE_ENV=production
        RUN npm install -g pnpm && pnpm install
        EXPOSE 3000
        CMD ["pnpm", "start"]
    image: quetre
    container_name: quetre
    restart: unless-stopped
    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.quetre.rule=Host(`${QUETRE_HOSTNAME?}`)"
      - "traefik.http.routers.quetre.entrypoints=websecure"
      - "traefik.http.routers.quetre.tls.certresolver=letsencrypt"
      - "traefik.http.routers.quetre.middlewares=authelia@docker"
      - "traefik.http.services.quetre.loadbalancer.server.port=3000"
    profiles:
      - quetre
      - all
