services:
  autosync:
    image: ghcr.io/pukabyte/autosync:latest
    container_name: autosync
    restart: unless-stopped
    expose:
      - 3536
    environment:
      - TZ=${TZ:-Etc/UTC}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=022
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.autosync.rule=Host(`${AUTOSYNC_HOSTNAME?}`)"
      - "traefik.http.routers.autosync.entrypoints=websecure"
      - "traefik.http.routers.autosync.tls.certresolver=letsencrypt"
      - "traefik.http.routers.autosync.middlewares=authelia@docker"
      - "traefik.http.services.autosync.loadbalancer.server.port=3536"
    volumes:
      - ./config.yaml:/app/config.yaml
      - /etc/localtime:/etc/localtime:ro
      - /mnt:/mnt:rslave
    depends_on:
      sonarr:
        condition: service_healthy
      sonarr4k:
        condition: service_healthy
      sonarranime:
        condition: service_healthy
      radarr:
        condition: service_healthy
      radarr4k:
        condition: service_healthy
      radarranime:
        condition: service_healthy
    profiles:
      - all
      - autosync
      - debrid_media_server
