log_level: DEBUG
sync_delay: 5s
sync_interval: 2s
webhook_events:
  sonarr:
  - Grab
  - Download
  - Rename
  - SeriesDelete
  - SeriesAdd
  - EpisodeFileDelete
  - Import
  radarr:
  - Grab
  - Download
  - Rename
  - MovieAdded
  - MovieDelete
  - MovieFileDelete
  - Import
media_servers:
- name: xenos
  type: jellyfin
  url: http://jellyfin:8096
  api_key: 
  enabled: true
- name: Xenos
  type: plex
  url: http://plex:32400
  enabled: true
  token: 
instances:
- name: Sonarr 1080p
  type: sonarr
  url: http://sonarr:8989
  api_key: 
  root_folder_path: /mnt/media/TV
  quality_profile_id: 7
  search_on_sync: true
  enabled_events:
  - SeriesAdd
  language_profile_id: 1
  season_folder: false
- name: Sonarr 4K
  type: sonarr
  url: http://sonarr4k:8989
  api_key: 
  root_folder_path: /mnt/media/TV - 4K
  quality_profile_id: 7
  search_on_sync: true
  enabled_events:
  - SeriesAdd
  language_profile_id: 1
  season_folder: false
- name: Radarr 1080p
  type: radarr
  url: http://radarr:7878
  api_key: 
  root_folder_path: /mnt/media/Movies
  quality_profile_id: 7
  search_on_sync: true
  enabled_events:
  - MovieAdded
- name: Radarr 4K
  type: radarr
  url: http://radarr4k:7878
  api_key: 
  root_folder_path: /mnt/media/Movies - 4K
  quality_profile_id: 7
  search_on_sync: true
  enabled_events:
  - MovieAdded
