services:
  webstreamr:
    image: webstreamr
    container_name: webstreamr
    restart: unless-stopped
    build:
      context: https://github.com/webstreamr/webstreamr.git
      dockerfile: Dockerfile
    expose:
      - 51546
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webstreamr.rule=Host(`${WEBSTREAMR_HOSTNAME?}`)"
      - "traefik.http.routers.webstreamr.entrypoints=websecure"
      - "traefik.http.routers.webstreamr.tls.certresolver=letsencrypt"
      - "traefik.http.routers.webstreamr.middlewares=authelia@docker"
      - "traefik.http.services.webstreamr.loadbalancer.server.port=51546"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:51546/manifest.json",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    profiles:
      - webstreamr
      - all
