services:
  blackhole:
    image: ghcr.io/westsurname/scripts/blackhole:latest
    container_name: blackhole
    user: "${PUID}:${PGID}"
    volumes:
      - ${REALDEBRID_MOUNT_TORRENTS_PATH:-/dev/null}:${REALDEBRID_MOUNT_TORRENTS_PATH:-/dev/null}
      - ${TORBOX_MOUNT_TORRENTS_PATH:-/dev/null}:${TORBOX_MOUNT_TORRENTS_PATH:-/dev/null}
      - ${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_SONARR_PATH}:/${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_SONARR_PATH}
      - ${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_RADARR_PATH}:/${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_RADARR_PATH}
      - ${DOCKER_DATA_DIR}/wests-scripts/blackhole/default/logs:/app/logs
      - /mnt:/mnt:rslave
    env_file:
      - ../.env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - SONARR_HOST=${SONARR_HOST}
      - SONARR_API_KEY=${SONARR_API_KEY}
      - RADARR_HOST=${RADARR_HOST}
      - RADARR_API_KEY=${RADARR_API_KEY}
      - BLACKHOLE_BASE_WATCH_PATH=${BLACKHOLE_BASE_WATCH_PATH}
    restart: unless-stopped
    depends_on:
      rclone:
        condition: service_started
      sonarr:
        condition: service_healthy
      radarr: 
        condition: service_healthy
    profiles:
      - debrid_media_server
      - all


  blackhole4k:
    image: ghcr.io/westsurname/scripts/blackhole:latest
    container_name: blackhole4k
    user: "${PUID}:${PGID}"
    volumes:
      - ${REALDEBRID_MOUNT_TORRENTS_PATH:-/dev/null}:${REALDEBRID_MOUNT_TORRENTS_PATH:-/dev/null}
      - ${TORBOX_MOUNT_TORRENTS_PATH:-/dev/null}:${TORBOX_MOUNT_TORRENTS_PATH:-/dev/null}
      - ${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_SONARR_PATH}4k:/${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_SONARR_PATH}
      - ${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_RADARR_PATH}4k:/${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_RADARR_PATH}
      - ${DOCKER_DATA_DIR}/wests-scripts/blackhole/4k/logs:/app/logs
      - /mnt:/mnt:rslave
    env_file:
      - ../.env
    environment:
      - BLACKHOLE_BASE_WATCH_PATH=${BLACKHOLE_BASE_WATCH_PATH}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - SONARR_HOST=${SONARR_HOST_4K}
      - SONARR_API_KEY=${SONARR_API_KEY_4K}
      - RADARR_HOST=${RADARR_HOST_4K}
      - RADARR_API_KEY=${RADARR_API_KEY_4K}
      - SONARR_ROOT_FOLDER=${SONARR_ROOT_FOLDER_4K}
      - RADARR_ROOT_FOLDER=${RADARR_ROOT_FOLDER_4K}
    restart: unless-stopped
    depends_on:
      rclone:
        condition: service_started
      sonarr4k:
        condition: service_healthy
      radarr4k:
        condition: service_healthy
    profiles:
      - debrid_media_server
      - all
    

    
  blackholeanime:
    image: ghcr.io/westsurname/scripts/blackhole:latest
    container_name: blackholeanime
    user: "${PUID}:${PGID}"
    volumes:
      - ${REALDEBRID_MOUNT_TORRENTS_PATH:-/dev/null}:${REALDEBRID_MOUNT_TORRENTS_PATH:-/dev/null}
      - ${TORBOX_MOUNT_TORRENTS_PATH:-/dev/null}:${TORBOX_MOUNT_TORRENTS_PATH:-/dev/null}
      - ${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_SONARR_PATH}anime:/${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_SONARR_PATH}
      - ${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_RADARR_PATH}anime:/${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_RADARR_PATH}
      - ${DOCKER_DATA_DIR}/wests-scripts/blackhole/anime/logs:/app/logs
      - /mnt:/mnt:rslave
    env_file:
      - ../.env
    environment:
      - BLACKHOLE_BASE_WATCH_PATH=${BLACKHOLE_BASE_WATCH_PATH}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - SONARR_HOST=${SONARR_HOST_ANIME}
      - SONARR_API_KEY=${SONARR_API_KEY_ANIME}
      - RADARR_HOST=${RADARR_HOST_ANIME}
      - RADARR_API_KEY=${RADARR_API_KEY_ANIME}
      - SONARR_ROOT_FOLDER=${SONARR_ROOT_FOLDER_ANIME}
      - RADARR_ROOT_FOLDER=${RADARR_ROOT_FOLDER_ANIME}

    restart: unless-stopped
    depends_on:
      rclone:
        condition: service_started
      sonarranime:
        condition: service_healthy
      radarranime:
        condition: service_healthy
    profiles:
      - debrid_media_server
      - all
    

