services:
  zipline:
    image: ghcr.io/diced/zipline:v4
    container_name: zipline
    restart: unless-stopped
    user: $PUID:$PGID
    expose:
      - 3000
    environment:
      - DATABASE_URL=postgres://zipline:postgres@zipline_postgres:5432/zipline
      - CORE_SECRET=${ZIPLINE_CORE_SECRET?}
    depends_on:
      zipline_postgres:
        condition: service_healthy
    volumes:
      - '${DOCKER_DATA_DIR}/zipline/uploads:/zipline/uploads'
      - '${DOCKER_DATA_DIR}/zipline/public:/zipline/public'
      - '${DOCKER_DATA_DIR}/zipline/themes:/zipline/themes'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zipline.rule=Host(`${ZIPLINE_HOSTNAME?}`)"
      - "traefik.http.routers.zipline.entrypoints=websecure"
      - "traefik.http.routers.zipline.tls.certresolver=letsencrypt"
    profiles:
      - zipline
      - all
    
  zipline_postgres:
    image: postgres:16
    restart: unless-stopped
    container_name: zipline_postgres
    volumes:
      - ${DOCKER_DATA_DIR}/zipline/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: zipline
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zipline
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zipline"]
      start_period: 1m
    profiles:
      - zipline
      - all
