services:
  plex_authentication:
    image: ghcr.io/westsurname/scripts/plex_authentication:latest
    container_name: plex_authentication_service
    restart: unless-stopped
    volumes:
      - ${DOCKER_DATA_DIR}/wests-scripts/shared/tokens.json:/app/shared/tokens.json
      - ${DOCKER_DATA_DIR}/wests-scripts/sockets:/app/sockets
    env_file:
      - ../.env
    profiles:
      - all
      - plex_request
      - plex_watchlist
