services:
  minecraft:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    container_name: minecraft
    ports:
      - "25565:25565"
    environment:
      UID: ${PUID}
      PGID: ${PGID}
      EULA: "TRUE"
      TYPE: ${MINECRAFT_SERVER_TYPE:-PAPER}
      MEMORY: ${MINECRAFT_SERVER_MEMORY:-8G}
      MOTD: ${MINECRAFT_SERVER_MOTD:-"A Minecraft Server"}
      OVERRIDE_ICON: ${MINECRAFT_SERVER_OVERRIDE_ICON:-}
      ICON: ${MINECRAFT_SERVER_ICON:-}
      USE_AIKAR_FLAGS: "TRUE"
      TZ: ${TZ:-UTC}
      DIFFICULTY: "2"
      VIEW_DISTANCE: ${MINECRAFT_SERVER_VIEW_DISTANCE:-10}
      OPS: |-
        ${MINECRAFT_SERVER_OP:-}
      ENABLE_WHITE_LIST: ${MINECRAFT_SERVER_ENABLE_WHITE_LIST:-false}
      WHITELIST: ${MINECRAFT_SERVER_WHITELIST:-}
    volumes:
      - "${DOCKER_DATA_DIR}/minecraft:/data"
    profiles:
      - minecraft
      - all
