services:
  apprise:
    image: lscr.io/linuxserver/apprise-api:latest
    container_name: apprise-api
    restart: unless-stopped
    expose:
      - 8000
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - APPRISE_ATTACH_SIZE=${MAX_ATTACHMENT_SIZE:-0}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apprise-api.rule=Host(`${APPRISE_HOSTNAME?}`)"
      - "traefik.http.routers.apprise-api.entrypoints=websecure"
      - "traefik.http.routers.apprise-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.apprise-api.loadbalancer.server.port=8000"
    volumes:
      - ${DOCKER_DATA_DIR}/apprise/config:/config
      - ${DOCKER_DATA_DIR}/apprise/attachments:/attachments
    profiles:
      - apprise
      - all
