services:
  zurg: 
    image: ghcr.io/debridmediamanager/${ZURG_REPO:-zurg-testing}:${ZURG_VERSION:-v0.9.3-final}
    container_name: zurg
    restart: unless-stopped
    healthcheck:
      test: curl -f localhost:9999/dav/version.txt || exit 1
    volumes:
      - ./config-${ZURG_CONFIG_VERSION:-v0.9}.yml:/app/config.yml
      - ${DOCKER_DATA_DIR}/zurg/data:/app/data
      - ${DOCKER_DATA_DIR}/zurg/logs:/app/logs
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.zurg.rule=Host(`${ZURG_HOSTNAME?}`)"
      - "traefik.http.routers.zurg.entrypoints=websecure"
      - "traefik.http.routers.zurg.tls.certresolver=letsencrypt"
      - "traefik.http.routers.zurg.middlewares=authelia@docker"
    profiles:
      - all
      - zurg
      - debrid_media_server

  rclone:
    image: rclone/rclone:latest
    container_name: rclone
    restart: unless-stopped
    environment:
      TZ: ${TZ:-UTC}
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - /mnt/remote/realdebrid:/data:rshared
      - ./rclone.conf:/config/rclone/rclone.conf
      - /mnt:/mnt
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    depends_on:
      zurg:
        condition: service_healthy
        restart: true
    command: >
      mount zurg: /data
      --allow-non-empty
      --allow-other
      --uid=${PUID}
      --gid=${PGID}
      --umask=002
      --attr-timeout 10y
      --buffer-size 64M
      --dir-cache-time 120s
      --poll-interval 60s
      --vfs-cache-max-age 2M
      --vfs-cache-max-size 30G
      --vfs-cache-min-free-space 1G
      --vfs-cache-mode full
      --vfs-cache-poll-interval 30s
      --vfs-disk-space-total-size 32G
      --vfs-fast-fingerprint
      --vfs-read-ahead 64M
      --vfs-read-chunk-size 1M
      --vfs-read-chunk-size-limit 32M
      --vfs-read-wait 40ms
      --vfs-refresh
      --transfers 16
      --checkers 16
      --multi-thread-streams 8
    profiles:
      - all
      - zurg
      - debrid_media_server
