# =================================== #
# ███████╗██╗   ██╗██████╗  ██████╗   #
# ╚══███╔╝██║   ██║██╔══██╗██╔════╝   #
#   ███╔╝ ██║   ██║██████╔╝██║  ███╗  #
#  ███╔╝  ██║   ██║██╔══██╗██║   ██║  #
# ███████╗╚██████╔╝██║  ██║╚██████╔╝  #
# ╚══════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝   #
# =================================== #

# ==============================================================================
#                           BASIC CONFIGURATION
# ==============================================================================
# Zurg configuration version 
zurg: v1

# Your Real-Debrid API token
# Get it from https://real-debrid.com/apitoken
token: 

# If you have other Real-Debrid tokens, you can uncomment the lines below and add them here
# download_tokens:
#   - MY_TOKEN_2
#   - MY_TOKEN_3
# ==============================================================================
#                          CORE SETTINGS
# ==============================================================================

host: "[::]"
port: 9999
# proxy: "http://warp:1080"
force_ipv6: false
number_of_hosts: 3

# ==============================================================================
#                         PERFORMANCE AND RATE LIMITS
# ==============================================================================

concurrent_workers: 32
api_rate_limit_per_minute: 60
torrents_rate_limit_per_minute: 25
api_timeout_secs: 15
download_timeout_secs: 10
retries_until_failed: 2
retry_503_errors: false 
fetch_torrents_page_size: 1000

# ==============================================================================
#                         FILE MANAGEMENT
# ==============================================================================

# Enable automatic torrent repair
enable_repair: true

# Action for RAR files: extract, delete, or none (default: "none")
rar_action: none

# Additional file extensions to consider as playable
# addl_playable_extensions:
#   - m3u
#   - jpg

# If a torrent contains any file with these extensions, delete the torrent
# delete_torrent_if_extensions_found:
#   - zipx
#   - rar

# Even when files are not selected in the torrent, if the file is playable (video or addl_playable_extensions), it will be selected
force_select_playable_files: false

# Retain the torrent name extension which is used for directory names (useful for single file torrents)
retain_folder_name_extension: true

# Retain the name value of a torrent from real-debrid (if false, will use original_name instead)
retain_rd_torrent_name: true

# Delete torrents that have encountered an error
delete_error_torrents: false

# Hide torrents that are broken (unplayable)
hide_broken_torrents: false

# Will ignore rename values in the torrent
ignore_renames: true

# Whether to safe .STRM files
save_strm_files: false

# ==============================================================================
#                      SCHEDULING AND UPDATES
# ==============================================================================

# How often to check for changes in the library (default: 15 seconds)
check_for_changes_every_secs: 20

# How often to check for broken torrents and repair them (default: 60 minutes)
repair_every_mins: 60

# How often to check for new downloads (unrestricted links, file locker links) (default: 720 minutes)
downloads_every_mins: 720

# How often to dump your library torrents to the dump folder for backup (default: 1440 minutes)
dump_torrents_every_mins: 1440

# Command to run when the library is updated (useful for plex refresh)
# on_library_update: "sh plex_update.sh \"$@\""



# ==============================================================================
#                         MEDIA ANALYSIS
# ==============================================================================


auto_analyze_new_torrents: false
cache_network_test_results: true


# ==============================================================================
#                         ADVANCED SETTINGS
# ==============================================================================

disable_stream_proxy: false
