# =================================== #
# ███████╗██╗   ██╗██████╗  ██████╗   #
# ╚══███╔╝██║   ██║██╔══██╗██╔════╝   #
#   ███╔╝ ██║   ██║██████╔╝██║  ███╗  #
#  ███╔╝  ██║   ██║██╔══██╗██║   ██║  #
# ███████╗╚██████╔╝██║  ██║╚██████╔╝  #
# ╚══════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝   #
# =================================== #


# Zurg configuration version
zurg: v1

# Provide your Real-Debrid API token
token: YOUR_RD_API_TOKEN # https://real-debrid.com/apitoken

# Host and port settings
host: "[::]"
port: 9999

concurrent_workers: 32

# Checking for changes in Real-Debrid API more frequently (every 60 seconds)
check_for_changes_every_secs: 15

# File handling and renaming settings
retain_rd_torrent_name: true
retain_folder_name_extension: true
expose_full_path: true

# Torrent management settings
enable_repair: true
auto_delete_rar_torrents: false

# Streaming and download link verification settings
serve_from_rclone: false
verify_download_link: false

# Network and API settings
force_ipv6: false