services:
  torbox-media-center:
    image: anonymoussystems/torbox-media-center:main
    container_name: torbox-media-center
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
      - TORBOX_API_KEY=${TORBOX_API_KEY}
      - MOUNT_METHOD=${TORBOX_MOUNT_METHOD}
      - MOUNT_PATH=/torbox
    volumes:
      - ${TORBOX_MOUNT_PATH}:/torbox
    profiles:
      - debrid_media_server
      - all
