services:
  repair:
    image: ghcr.io/westsurname/scripts/scripts:latest
    container_name: repair
    command: python repair.py --no-confirm
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      - SONARR_HOST=${SONARR_HOST}
      - SONARR_API_KEY=${SONARR_API_KEY}
      - RADARR_HOST=${RADARR_HOST}
      - RADARR_API_KEY=${RADARR_API_KEY}
    volumes: 
      - ${REALDEBRID_MOUNT_TORRENTS_PATH:-/dev/null}:${REALDEBRID_MOUNT_TORRENTS_PATH:-/dev/null}
      - ${TORBOX_MOUNT_TORRENTS_PATH:-/dev/null}:${TORBOX_MOUNT_TORRENTS_PATH:-/dev/null}
      - ${SONARR_ROOT_FOLDER}:${SONARR_ROOT_FOLDER}
      - ${RADARR_ROOT_FOLDER}:${RADARR_ROOT_FOLDER}
    depends_on:
      rclone:
        condition: service_started
      sonarr:
        condition: service_healthy
      radarr: 
        condition: service_healthy
    profiles:
      - debrid_media_server
      - all

  repair4k:
    image: ghcr.io/westsurname/scripts/scripts:latest
    container_name: repair4k
    command: python repair.py --no-confirm
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      - SONARR_HOST=${SONARR_HOST_4K}
      - SONARR_API_KEY=${SONARR_API_KEY_4K}
      - RADARR_HOST=${RADARR_HOST_4K}
      - RADARR_API_KEY=${RADARR_API_KEY_4K}
    volumes: 
      - ${REALDEBRID_MOUNT_TORRENTS_PATH:-/dev/null}:${REALDEBRID_MOUNT_TORRENTS_PATH:-/dev/null}
      - ${TORBOX_MOUNT_TORRENTS_PATH:-/dev/null}:${TORBOX_MOUNT_TORRENTS_PATH:-/dev/null}
      - ${SONARR_ROOT_FOLDER_4K}:${SONARR_ROOT_FOLDER_4K}
      - ${RADARR_ROOT_FOLDER_4K}:${RADARR_ROOT_FOLDER_4K}
    depends_on:
      rclone:
        condition: service_started
      sonarr4k:
        condition: service_healthy
      radarr4k: 
        condition: service_healthy
    profiles:
      - debrid_media_server
      - all

  repairanime:
    image: ghcr.io/westsurname/scripts/scripts:latest
    container_name: repairanime
    command: python repair.py --no-confirm
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      - SONARR_HOST=${SONARR_HOST_ANIME}
      - SONARR_API_KEY=${SONARR_API_KEY_ANIME}
      - RADARR_HOST=${RADARR_HOST_ANIME}
      - RADARR_API_KEY=${RADARR_API_KEY_ANIME}
    volumes: 
      - ${REALDEBRID_MOUNT_TORRENTS_PATH:-/dev/null}:${REALDEBRID_MOUNT_TORRENTS_PATH:-/dev/null}
      - ${TORBOX_MOUNT_TORRENTS_PATH:-/dev/null}:${TORBOX_MOUNT_TORRENTS_PATH:-/dev/null}
      - ${SONARR_ROOT_FOLDER_ANIME}:${SONARR_ROOT_FOLDER_ANIME}
      - ${RADARR_ROOT_FOLDER_ANIME}:${RADARR_ROOT_FOLDER_ANIME}
    depends_on:
      rclone:
        condition: service_started
      sonarranime:
        condition: service_healthy
      radarranime: 
        condition: service_healthy
    profiles:
      - debrid_media_server
      - all
