services:
  yamtrack:
    image: ghcr.io/fuzzygrim/yamtrack
    container_name: yamtrack
    restart: unless-stopped
    expose:
      - 8000
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.yamtrack.rule=Host(`${YAMTRACK_HOSTNAME?}`)"
      - "traefik.http.routers.yamtrack.entrypoints=websecure"
      - "traefik.http.routers.yamtrack.tls.certresolver=letsencrypt"
      - "traefik.http.routers.yamtrack.middlewares=authelia@docker"
    volumes:
      - ${DOCKER_DATA_DIR}/yamtrack/db:/yamtrack/db
    depends_on:
      - yamtrack_redis
    profiles:
      - yamtrack
      - all
    

  yamtrack_redis:
    image: redis:7-alpine
    container_name: yamtrack-redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ${DOCKER_DATA_DIR}/yamtrack/cache:/data
    profiles:
      - yamtrack
      - all


